using System.Globalization;

namespace AngularMovieAPI2.Helper
{
    // Custom exception class for throwing application specific exceptions ( for example for validation)
    // That can be caught and handled within the application
    //The app exception is a custom exceptions class used to differentiate between handled and unhandled exceptions.
    //Handled exceptions are ones generated by the application and used to display friendly error messages to the client, for example business logic or validation exceptions caused by incorrect input from the user.
    //Unhandled exceptions are generated by the .NET framework and caused by bugs in the application code.

    public class AppException:Exception
    {
        public AppException() : base()
        {
        }
        public AppException(string message) : base(message)
        {
        }
        public AppException(string message, params object[] args) : base(String.Format(CultureInfo.CurrentCulture, message, args))
        {

        }
    }
}
